#!/usr/bin/env python3
"""
Reels Publisher — DEVOPSRAIZ
============================

Publica vídeos no Instagram como Reels usando a Meta Graph API (v21.0).

Fluxo:
  1. Recebe caminho local do MP4 (ou gera via HeyGen)
  2. Faz upload do MP4 pra um storage público (GitHub Releases por padrão,
     também suporta Cloudflare R2/S3)
  3. Chama POST /{ig_user}/media com media_type=REELS e video_url
  4. Faz polling até container ficar FINISHED
  5. POST /{ig_user}/media_publish

Uso:
    # Publica o Reel do dia atual (gera vídeo via HeyGen + publica)
    python reels_publisher.py auto --today

    # Publica um Reel específico do calendário
    python reels_publisher.py auto --day 3

    # Pula a geração (MP4 já existe em ../videos_mp4/reel-dia-NN.mp4)
    python reels_publisher.py publish --day 3

    # Só gera o vídeo (não publica)
    python reels_publisher.py generate --day 3
"""

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import date, datetime
from pathlib import Path

import requests
from openpyxl import load_workbook

# Reusa helpers do instagram_publisher.py
sys.path.insert(0, str(Path(__file__).parent))
from instagram_publisher import (
    load_env, load_calendar, build_caption, GRAPH, IGClient,
)
from heygen_client import HeyGenClient


# Mapeia número do dia → roteiro → arquivo MP4 esperado
REEL_MAP = {
    1: ("reel-dia-01-apresentacao.txt", "reel-dia-01.mp4"),
    3: ("reel-dia-03-salario-devops.txt", "reel-dia-03.mp4"),
    9: ("reel-dia-09-terraform-30s.txt", "reel-dia-09.mp4"),
    16: ("reel-dia-16-docker-imagem.txt", "reel-dia-16.mp4"),
    21: ("reel-dia-21-timelapse.txt", "reel-dia-21.mp4"),
    26: ("reel-dia-26-projeto-para-saas.txt", "reel-dia-26.mp4"),
}


class ReelsIGClient(IGClient):
    """Estende IGClient com suporte a Reels (media_type=REELS)."""

    def create_reel_container(self, video_url: str, caption: str,
                              share_to_feed: bool = True) -> str:
        resp = self._post(f"{self.ig_id}/media", {
            "media_type": "REELS",
            "video_url": video_url,
            "caption": caption,
            "share_to_feed": "true" if share_to_feed else "false",
        })
        return resp["id"]

    def create_story_container(self, video_url: str) -> str:
        resp = self._post(f"{self.ig_id}/media", {
            "media_type": "STORIES",
            "video_url": video_url,
        })
        return resp["id"]


# --------------------------------------------------- upload de MP4 público --
def upload_to_github_releases(mp4_path: str, cfg: dict) -> str:
    """
    Faz upload do MP4 como asset de um GitHub Release.
    Precisa de: GITHUB_TOKEN, GITHUB_REPO (ex: 'devopsraiz/ig-assets')
    Cria (ou reutiliza) o release 'instagram-assets' e anexa o arquivo.
    Retorna URL público do asset.
    """
    token = cfg.get("GITHUB_TOKEN")
    repo = cfg.get("GITHUB_REPO")
    if not token or not repo:
        raise RuntimeError(
            "Configure GITHUB_TOKEN e GITHUB_REPO no .env para upload automático."
        )
    filename = Path(mp4_path).name
    tag = cfg.get("GITHUB_RELEASE_TAG", "v1.0.0")
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }
    # 1) Garante que o release existe
    r = requests.get(
        f"https://api.github.com/repos/{repo}/releases/tags/{tag}",
        headers=headers, timeout=30,
    )
    if r.status_code == 404:
        r = requests.post(
            f"https://api.github.com/repos/{repo}/releases",
            headers=headers,
            json={"tag_name": tag, "name": "Instagram Assets",
                  "body": "Auto-generated by reels_publisher.py"},
            timeout=30,
        )
    r.raise_for_status()
    release = r.json()
    release_id = release["id"]

    # 2) Remove asset com mesmo nome se já existir (idempotência)
    for asset in release.get("assets", []):
        if asset["name"] == filename:
            requests.delete(asset["url"], headers=headers, timeout=30)

    # 3) Upload do novo asset
    upload_url = release["upload_url"].split("{")[0]
    with open(mp4_path, "rb") as f:
        data = f.read()
    r = requests.post(
        upload_url,
        headers={**headers, "Content-Type": "video/mp4"},
        params={"name": filename},
        data=data,
        timeout=600,
    )
    r.raise_for_status()
    return r.json()["browser_download_url"]


def upload_to_r2(mp4_path: str, cfg: dict) -> str:
    """
    Alternativa: Cloudflare R2 (ou S3 compatible).
    Precisa de: R2_ENDPOINT, R2_ACCESS_KEY, R2_SECRET_KEY, R2_BUCKET, R2_PUBLIC_URL
    Usa boto3 se disponível; fallback via curl.
    """
    import boto3
    s3 = boto3.client(
        "s3",
        endpoint_url=cfg["R2_ENDPOINT"],
        aws_access_key_id=cfg["R2_ACCESS_KEY"],
        aws_secret_access_key=cfg["R2_SECRET_KEY"],
        region_name="auto",
    )
    filename = Path(mp4_path).name
    s3.upload_file(mp4_path, cfg["R2_BUCKET"], filename,
                   ExtraArgs={"ContentType": "video/mp4"})
    return f"{cfg['R2_PUBLIC_URL'].rstrip('/')}/{filename}"


def upload_mp4(mp4_path: str, cfg: dict) -> str:
    """Escolhe backend de upload baseado em config."""
    if cfg.get("VIDEO_HOSTING", "github").lower() == "r2":
        return upload_to_r2(mp4_path, cfg)
    return upload_to_github_releases(mp4_path, cfg)


# --------------------------------------------------------- full pipeline --
def generate_video(day: int, cfg: dict) -> str:
    """Gera MP4 via HeyGen a partir do roteiro correspondente."""
    if day not in REEL_MAP:
        raise ValueError(f"Dia {day} não tem Reel mapeado em REEL_MAP")
    script_name, mp4_name = REEL_MAP[day]
    base = Path(__file__).parent.parent
    script_path = base / "roteiros" / script_name
    mp4_path = base / "videos_mp4" / mp4_name

    if mp4_path.exists() and cfg.get("REGENERATE", "false").lower() != "true":
        print(f"  ✓ MP4 já existe: {mp4_path}")
        return str(mp4_path)

    if not script_path.exists():
        raise FileNotFoundError(f"Roteiro não encontrado: {script_path}")

    # Limpa o roteiro (remove direções entre [colchetes] e cabeçalho)
    raw = script_path.read_text(encoding="utf-8")
    if "==========" in raw:
        raw = raw.split("===============================================")[-1]
    clean_lines = []
    for line in raw.splitlines():
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            continue
        clean_lines.append(line)
    script_text = "\n".join(clean_lines).strip()

    client = HeyGenClient(
        cfg["HEYGEN_API_KEY"],
        cfg["HEYGEN_AVATAR_ID"],
        cfg["HEYGEN_VOICE_ID"],
    )
    print(f"  → HeyGen: gerando ({len(script_text)} chars)...")
    video_id = client.generate(script_text)
    print(f"    video_id = {video_id}")
    url = client.wait_for_video(video_id)
    client.download(url, str(mp4_path))
    print(f"  ✓ MP4 salvo em {mp4_path}")
    return str(mp4_path)


def publish_reel(day: int, cfg: dict, mp4_path: str | None = None) -> str:
    posts = load_calendar(cfg["CALENDAR_XLSX_ABS"])
    post = next((p for p in posts if int(p["Dia"]) == day), None)
    if not post:
        raise ValueError(f"Post do dia {day} não encontrado no calendário")

    if day not in REEL_MAP:
        raise ValueError(f"Dia {day} não tem Reel mapeado. Use o publisher de photo.")
    _, mp4_name = REEL_MAP[day]

    caption = build_caption(post)
    print(f"→ Publicando Reel Dia {day}: {post['Titulo / Gancho']}")

    # Se VIDEO_BASE_URL está configurado (repo público), usa raw URL direto
    # Caso contrário, faz upload pro release via GitHub API
    if cfg.get("VIDEO_BASE_URL"):
        video_url = f"{cfg['VIDEO_BASE_URL'].rstrip('/')}/{mp4_name}"
        print(f"  • Video URL (raw repo): {video_url}")
    else:
        if mp4_path is None:
            mp4_path = str(Path(__file__).parent.parent / "videos_mp4" / mp4_name)
        if not Path(mp4_path).exists():
            raise FileNotFoundError(f"MP4 não encontrado em {mp4_path} — gere antes com `generate`")
        print("  • Upload do MP4 para hosting público...")
        video_url = upload_mp4(mp4_path, cfg)
        print(f"    URL: {video_url}")

    ig = ReelsIGClient(cfg["IG_USER_ID"], cfg["META_ACCESS_TOKEN"])
    print("  • Criando container Reel na Meta...")
    container_id = ig.create_reel_container(video_url, caption, share_to_feed=True)
    print(f"    container: {container_id}")

    print("  • Aguardando Meta processar o vídeo (pode levar 1-5 min)...")
    ig.wait_container_ready(container_id, timeout=600)

    print("  • Publicando...")
    media_id = ig.publish(container_id)
    print(f"✓ REEL PUBLICADO! media_id = {media_id}")

    _log({
        "type": "reel",
        "dia": day,
        "media_id": media_id,
        "video_url": video_url,
        "publicado_em": datetime.utcnow().isoformat(),
    })
    return media_id


def _log(entry: dict):
    log_path = Path(__file__).parent / "publish_log.jsonl"
    with log_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


def _today_day() -> int:
    start = date(2026, 4, 21)
    return (date.today() - start).days + 1


# ------------------------------------------------------------------- cli --
def main():
    parser = argparse.ArgumentParser(description="Publica Reels DEVOPSRAIZ full-auto")
    sub = parser.add_subparsers(dest="cmd", required=True)

    auto = sub.add_parser("auto", help="Gera vídeo via HeyGen + publica no Instagram")
    g1 = auto.add_mutually_exclusive_group(required=True)
    g1.add_argument("--day", type=int)
    g1.add_argument("--today", action="store_true")

    pub = sub.add_parser("publish", help="Publica MP4 existente sem gerar")
    pub.add_argument("--day", type=int, required=True)
    pub.add_argument("--mp4", help="Caminho customizado do MP4")

    gen = sub.add_parser("generate", help="Só gera o vídeo HeyGen (não publica)")
    gen.add_argument("--day", type=int, required=True)

    args = parser.parse_args()
    cfg = load_env(Path(__file__).parent / ".env")
    cfg["CALENDAR_XLSX_ABS"] = str(
        (Path(__file__).parent / cfg.get("CALENDAR_XLSX",
         "../calendario-editorial-30-dias.xlsx")).resolve()
    )

    if args.cmd == "auto":
        day = args.day if args.day else _today_day()
        if day not in REEL_MAP:
            print(f"ℹ Dia {day} não é Reel — use instagram_publisher.py pra post de foto/carrossel")
            sys.exit(0)
        mp4 = generate_video(day, cfg)
        publish_reel(day, cfg, mp4)

    elif args.cmd == "publish":
        publish_reel(args.day, cfg, args.mp4)

    elif args.cmd == "generate":
        generate_video(args.day, cfg)


if __name__ == "__main__":
    main()
